@baseUrl = http://localhost:3001

###############################################################################
# AUTH ########################################################################
###############################################################################

###

## create user
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json


{ "name": "Rudney", "password": "12345678", "email": "teste1@gmail.com"}


###
