export const DECLINED_COOLDOWN_IN_DAYS = 30;
export const DECLINED_COOLDOWN_IN_MS =
  DECLINED_COOLDOWN_IN_DAYS * 24 * 60 * 60 * 1000;
export const POSTGRES_UNIQUE_VIOLATION_ERROR_CODE = '23505';
export const COLLAB_PAIR_UNIQUE_CONSTRAINT = 'uq_collab_pair';
